### ISSUE TITLE
Issue faced while trying to execute

### ISSUE THREAD

**Issue by atakrami** [DarriusL/CoCheLab#2]
Hi,
I have created a Python environment and tried to execute it. I am getting the following error:

[2023-12-25 06:53:52,044]-[INFO - lib.callback]      
Processing ./data/datasets/meta/ml-1m/ratings.dat ...
Traceback (most recent call last):
  File "C:\Users\saeed\Downloads\CoCheLab-main\CoCheLab-main\executor.py", line 30, in <module>
    run_pcr(cfg = dp_cfg);
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saeed\Downloads\CoCheLab-main\CoCheLab-main\data\generator.py", line 89, in run_pcr
    dataset = ml_generate(dp_cfg['src'])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saeed\Downloads\CoCheLab-main\CoCheLab-main\data\generator.py", line 47, in ml_generate
    mldataset = pcr.ml_pcr(src = src);
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saeed\Downloads\CoCheLab-main\CoCheLab-main\data\processor.py", line 170, in 
ml_pcr
    ml = np.loadtxt(src, dtype = int, usecols = (0, 1, 3));
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saeed\Downloads\CoCheLab-main\CoCheLab-main\myvenv\Lib\site-packages\numpy\lib\npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saeed\Downloads\CoCheLab-main\CoCheLab-main\myvenv\Lib\site-packages\numpy\lib\npyio.py", line 1016, in _read
    arr = _load_from_filelike(
          ^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string '1::1193::5::978300760' to int32 at row 0, column 1.

**Comment by DarriusL** [comment]
Sorry, I forgot to mention in the readme that the ml-1m data set requires manually replacing the delimiters in the file [ratings.dat] with spaces.

**Comment by atakrami** [comment]
[2023-12-26 16:46:26,513]-[INFO - lib.callback]
Processing ./data/datasets/meta/ml-1m/ratings.dat ...

[2023-12-26 16:46:43,440]-[INFO - lib.callback]
Processing ./data/datasets/meta/ml-1m/ratings.dat complete. time consuming:00 hour - 00 min - 16 s


[2023-12-26 16:46:43,441]-[INFO - lib.callback]
./data/datasets/meta/ml-1m/ratings.dat
Report
==============================
Users: 6040
Reqs: 3706
Interactions: 1000209
Avg Req Len: 165.60
Avg useful Req Len: 165.60
Sparsity: 0.9553
==============================


[2023-12-26 16:46:44,572]-[INFO - lib.callback]
Reprocessing, cut or fill to 55  ...

[2023-12-26 16:46:54,285]-[INFO - lib.callback]
Reprocessing, cut or fill to 55  ... complete. time consuming:00 hour - 00 min - 09 s


[2023-12-26 16:46:54,287]-[INFO - lib.callback]
divide dataset  ...

[2023-12-26 16:46:56,895]-[INFO - lib.callback]
divide dataset  ... complete.


[2023-12-26 16:46:56,897]-[INFO - lib.callback]
Processing ./data/datasets/meta/appliances/Appliances.json ...

[2023-12-26 16:46:56,992]-[INFO - lib.callback]
Processing ./data/datasets/meta/appliances/Appliances.json complete. time consuming:00 hour - 00 min - 00 s


[2023-12-26 16:46:56,993]-[INFO - lib.callback]
./data/datasets/meta/appliances/Appliances.json
Report
==============================
Users: 18
Reqs: 26
Interactions: 107
Avg Req Len: 5.94
Avg useful Req Len: 5.94
Sparsity: 0.7714
==============================


[2023-12-26 16:46:57,000]-[INFO - lib.callback]
Reprocessing, cut or fill to 25  ...

[2023-12-26 16:46:57,020]-[INFO - lib.callback]
Reprocessing, cut or fill to 25  ... complete. time consuming:00 hour - 00 min - 00 s


[2023-12-26 16:46:57,058]-[INFO - lib.callback]
divide dataset  ...

[2023-12-26 16:46:57,094]-[INFO - lib.callback]
divide dataset  ... complete.


[2023-12-26 16:46:57,095]-[INFO - lib.callback]
Processing ./data/datasets/process/lite/Digital_Music_lite.data ...
Traceback (most recent call last):
  File "C:\Users\saeed\Downloads\CoCheLab-main\CoCheLab-main\executor.py", line 30, in <module>
    run_pcr(cfg = dp_cfg);
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saeed\Downloads\CoCheLab-main\CoCheLab-main\data\generator.py", line 92, in run_pcr
    dataset = rev_generate(dp_cfg['src']);
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saeed\Downloads\CoCheLab-main\CoCheLab-main\data\generator.py", line 68, in rev_generate
    dataset = pcr.rev_pcr(src = src);
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saeed\Downloads\CoCheLab-main\CoCheLab-main\data\processor.py", line 210, in rev_pcr
    data = np.zeros((ju.jsonlen(src), 3), dtype = int);
                     ^^^^^^^^^^^^^^^
  File "C:\Users\saeed\Downloads\CoCheLab-main\CoCheLab-main\lib\json_util.py", line 69, in jsonlen
    f = open(src, 'r');
        ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/datasets/process/lite/Digital_Music_lite.data'

**Comment by atakrami** [comment]
![image](https://github.com/DarriusL/CoCheLab/assets/133939646/97a32a43-c507-4dcf-afc1-8da3a97413f1)

**Comment by DarriusL** [comment]
I changed the data processing configuration file before while debugging, but I forgot to change it back when I was done.
Just enter
<img width="160" alt="image" src="https://github.com/DarriusL/CoCheLab/assets/119288894/f536ee17-2e04-4e6b-9edd-10a5067eb4f4">
and change the configure into 
<img width="389" alt="image" src="https://github.com/DarriusL/CoCheLab/assets/119288894/f0451a28-8021-483b-ab2c-be7cfe660ac3">
And place the downloaded original json file in the corresponding path.

Also, I will also update the configuration file in the repository.

Thank you for your feedback

**Comment by atakrami** [comment]
Thanks for the update. There are some errors after doing the above-said correction. 

[2023-12-27 09:58:46,656]-[INFO - lib.callback]
Processing ./data/datasets/meta/ml-1m/ratings.dat ...

[2023-12-27 09:59:03,088]-[INFO - lib.callback]
Processing ./data/datasets/meta/ml-1m/ratings.dat complete. time consuming:00 hour - 00 min - 16 s


[2023-12-27 09:59:03,096]-[INFO - lib.callback]
./data/datasets/meta/ml-1m/ratings.dat
Report
==============================
Users: 6040
Reqs: 3706
Interactions: 1000209
Avg Req Len: 165.60
Avg useful Req Len: 165.60
Sparsity: 0.9553
==============================


[2023-12-27 09:59:04,271]-[INFO - lib.callback]
Reprocessing, cut or fill to 55  ...

[2023-12-27 09:59:13,580]-[INFO - lib.callback]
Reprocessing, cut or fill to 55  ... complete. time consuming:00 hour - 00 min - 09 s


[2023-12-27 09:59:13,585]-[INFO - lib.callback]
divide dataset  ...

[2023-12-27 09:59:16,012]-[INFO - lib.callback]
divide dataset  ... complete.


[2023-12-27 09:59:16,013]-[INFO - lib.callback]
Processing ./data/datasets/meta/appliances/Appliances.json ...

[2023-12-27 09:59:16,098]-[INFO - lib.callback]
Processing ./data/datasets/meta/appliances/Appliances.json complete. time consuming:00 hour - 00 min - 00 s


[2023-12-27 09:59:16,100]-[INFO - lib.callback]
./data/datasets/meta/appliances/Appliances.json
Report
==============================
Users: 18
Reqs: 26
Interactions: 107
Avg Req Len: 5.94
Avg useful Req Len: 5.94
Sparsity: 0.7714
==============================


[2023-12-27 09:59:16,106]-[INFO - lib.callback]
Reprocessing, cut or fill to 25  ...

[2023-12-27 09:59:16,126]-[INFO - lib.callback]
Reprocessing, cut or fill to 25  ... complete. time consuming:00 hour - 00 min - 00 s


[2023-12-27 09:59:16,172]-[INFO - lib.callback]
divide dataset  ...

[2023-12-27 09:59:16,206]-[INFO - lib.callback]
divide dataset  ... complete.


[2023-12-27 09:59:16,208]-[INFO - lib.callback]
Processing ./data/datasets/meta/lite/Digital_Music_lite.json ...
Traceback (most recent call last):
  File "C:\Users\saeed\Downloads\CoCheLab-main\CoCheLab-main\executor.py", line 30, in <module>
    run_pcr(cfg = dp_cfg);
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saeed\Downloads\CoCheLab-main\CoCheLab-main\data\generator.py", line 92, in run_pcr
    dataset = rev_generate(dp_cfg['src']);
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saeed\Downloads\CoCheLab-main\CoCheLab-main\data\generator.py", line 68, in rev_generate
    dataset = pcr.rev_pcr(src = src);
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saeed\Downloads\CoCheLab-main\CoCheLab-main\data\processor.py", line 210, in rev_pcr
    data = np.zeros((ju.jsonlen(src), 3), dtype = int);
                     ^^^^^^^^^^^^^^^
  File "C:\Users\saeed\Downloads\CoCheLab-main\CoCheLab-main\lib\json_util.py", line 69, in jsonlen
    f = open(src, 'r');
        ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/datasets/meta/lite/Digital_Music_lite.json'
(myvenv) PS C:\Users\saeed\Downloads\CoCheLab-main\CoCheLab-main>

**Comment by DarriusL** [comment]
This is a bit strange. Please check whether the file in path [./data/datasets/meta/lite] is [Digital_Music_lite.json], because the picture you sent before shows ***.data

**Comment by DarriusL** [comment]
<img width="664" alt="image" src="https://github.com/DarriusL/CoCheLab/assets/119288894/c5678578-b013-4187-9ff2-63d20830a7dc">
<img width="1183" alt="image" src="https://github.com/DarriusL/CoCheLab/assets/119288894/5bb2f7c6-82c9-4bd8-8494-fe151e36668b">
